my_set = set()
# my_set.add('curtains')
my_set.add('my uniform')
my_set.add('my stationery')
my_set.add('my rucksack')
my_set.add('my school books')
my_set.add('a padlock')
print(my_set)
my_set.add('a padlock')
print(my_set)